export default {
  "FaZe": 984,
  "Vitality": 768,
  "Spirit": 699,
  "MOUZ": 566,
  "G2": 495,
  "Natus Vincere": 486,
  "Virtus.pro": 390,
  "Falcons": 343,
  "Cloud9": 309,
  "ENCE": 300,
  "Apeks": 241,
  "HEROIC": 238,
  "Complexity": 237,
  "Eternal Fire": 230,
  "GamerLegion": 201,
  "FURIA": 181,
  "Monte": 151,
  "TheMongolz": 120,
  "Astralis": 118,
  "9 Pandas": 99,
  "Liquid": 90,
  "BetBoom": 88,
  "AMKAL": 80,
  "SAW": 79,
  "MIBR": 79,
  "HAVU": 78,
  "ECSTATIC": 74,
  "KOI": 73,
  "BIG": 72,
  "Imperial": 65,
  "Wildcard": 33,
  "Nouns": 29,
  "Elevate": 23,
  "BOSS": 22,
  "Party Astronauts": 14,
  "Carpe Diem": 10,
  "Mythic": 10,
  "my life be like": 9,
  "One More": 8,
  "Take Flyte": 6,
  "FLUFFY AIMERS": 6,
  "Zomblers": 5,
  "Limitless": 5,
  "Nouns fe": 2,
  "Shimmer": 2,
  "WG Bandits": 1,
  "Limitless Angels": 1,
  "COVEN": 0,
  "Legacy": 55,
  "paiN": 45,
  "ODDIK": 32,
  "RED Canids": 27,
  "Sharks": 20,
  "W7M": 19,
  "Fluxo": 18,
  "adalYamigos": 16,
  "Case": 16,
  "Flamengo": 11,
  "Galorys": 9,
  "Solid": 8,
  "2GAME": 5,
  "FURIA Academy": 5,
  "Corinthians": 4,
  "MIBR Academy": 3,
  "inSanitY": 2,
  "MIBR fe": 2,
  "Hype": 2,
  "O PLANO": 2,
  "W7M fe": 2,
  "Intense": 1,
  "GENKID4M4": 1,
  "Yawara": 1,
  "9z Academy": 1,
  "Divina fe": 1,
  "E-Xolos LAZER": 1,
  "SINNERS": 19,
  "ECLOT": 15,
  "UNiTY": 9,
  "Preasy": 51,
  "Espionage": 27,
  "Sprout": 15,
  "Astralis Talent": 9,
  "Sashi": 4,
  "XI": 3,
  "Sashi Academy": 1,
  "Astralis W": 1,
  "CEPTER": 1,
  "ENCE Academy": 15,
  "JANO": 11,
  "TMVG": 6,
  "Rounds": 4,
  "Heimo": 2,
  "VIOLET": 0,
  "ALTERNATE aTTaX": 7,
  "xGOD": 3,
  "hypewrld": 6,
  "EC BANGA": 1,
  "sunshine": 1,
  "Rebels": 61,
  "Enterprise": 46,
  "Permitta": 20,
  "ex-Anonymo": 10,
  "brazylijski luz": 9,
  "9INE": 8,
  "PGE Turow": 4,
  "lajtbitexe": 3,
  "NAVI Javelins": 3,
  "ThunderFlash": 2,
  "Aurora": 41,
  "FORZE": 31,
  "Nemiga": 30,
  "Insilio": 19,
  "Space": 17,
  "Spirit Academy": 17,
  "ILIN": 14,
  "RUBY": 13,
  "Linx Legacy": 12,
  "V1dar": 11,
  "RUSH B": 10,
  "Aurora Young Blud": 9,
  "DMS": 8,
  "VP.Prodigy": 7,
  "GR": 7,
  "GUN5": 4,
  "LEON": 3,
  "Fort Arena": 3,
  "Memo": 3,
  "OWL": 3,
  "CYBERSHOKE": 2,
  "Fearless Cheetahs": 2,
  "LYG": 2,
  "PARIVISION": 2,
  "Metizport": 35,
  "Young Ninjas": 18,
  "Johnny Speeds": 13,
  "EYEBALLERS": 13,
  "Alliance": 11,
  "Lilmix": 6,
  "GODSENT": 5,
  "Onliners5": 5,
  "B8": 14,
  "ex-ENEIDA": 13,
  "ESC": 12,
  "Passion UA": 10,
  "INGLORIOUS": 1,
  "Endpoint": 14,
  "Coalesce": 5,
  "Verdant": 3,
  "Lynn Vision": 44,
  "TYLOO": 27,
  "Rare Atom": 14,
  "Newhappy": 8,
  "E9": 8,
  "Steel Helmet": 7,
  "SHPL": 4,
  "Nirvana": 3,
  "DNA": 0,
  "2ez": 4,
  "True Rippers": 4,
  "Gods Reign": 3,
  "Grayfox": 1,
  "ATOX": 23,
  "The Huns": 12,
  "Eruption": 7,
  "Chinggis Warriors": 2,
  "Jeeves": 43,
  "Rooster": 15,
  "Bad News Kangaroos": 11,
  "sunday school": 8,
  "Vantage": 7,
  "VexX": 6,
  "DXA": 5,
  "Mindfreak": 5,
  "RKON": 4,
  "KZG": 4,
  "iM Apartments": 2,
  "LE-LUX": 1,
  "disciples": 1,
  "Canon Event": 1
} as Record<string, number>;