export default {
  "FaZe": 982,
  "MOUZ": 947,
  "Vitality": 745,
  "Natus Vincere": 723,
  "G2": 591,
  "Spirit": 430,
  "Astralis": 398,
  "Complexity": 331,
  "Virtus.pro": 309,
  "Eternal Fire": 294,
  "Liquid": 226,
  "TheMongolz": 172,
  "HEROIC": 163,
  "FlyQuest": 159,
  "paiN": 158,
  "FURIA": 148,
  "MIBR": 144,
  "Imperial": 134,
  "Falcons": 122,
  "BetBoom": 117,
  "SAW": 112,
  "ENCE": 110,
  "M80": 105,
  "3DMAX": 103,
  "BIG": 102,
  "Gaimin Gladiators": 93,
  "Monte": 89,
  "GamerLegion": 85,
  "Aurora": 84,
  "Sashi": 64,
  "Party Astronauts": 26,
  "BOSS": 24,
  "Wildcard": 18,
  "Nouns": 17,
  "NRG": 15,
  "Elevate": 14,
  "Mythic": 9,
  "Take Flyte": 9,
  "FLUFFY AIMERS": 8,
  "One More": 8,
  "Limitless": 7,
  "Carpe Diem": 3,
  "Shimmer": 3,
  "Karma": 2,
  "Nouns fe": 1,
  "my life be like": 1,
  "WG Bandits": 1,
  "COVEN": 0,
  "Legacy": 43,
  "RED Canids": 21,
  "Sharks": 17,
  "ODDIK": 16,
  "Fluxo": 15,
  "Galorys": 11,
  "Solid": 8,
  "inSanitY": 6,
  "Case": 6,
  "W7M": 6,
  "2GAME": 5,
  "Intense": 4,
  "Corinthians": 3,
  "Vikings KR": 3,
  "Fluxo Demons": 2,
  "Yawara": 2,
  "FURIA fe": 2,
  "MIBR fe": 2,
  "FURIA Academy": 2,
  "Atrix": 1,
  "Bounty Hunters": 1,
  "O PLANO": 1,
  "Hype": 1,
  "GENKID4M4": 0,
  "SINNERS": 20,
  "ECLOT": 13,
  "UNiTY": 6,
  "Grannys Knockers": 10,
  "MASONIC": 9,
  "CPH Wolves": 5,
  "Preasy": 5,
  "Astralis Talent": 4,
  "Sashi Academy": 2,
  "XI": 2,
  "Astralis W": 1,
  "WOPA": 1,
  "HAVU": 11,
  "ENCE Academy": 6,
  "Heimo": 5,
  "JANO": 4,
  "TMVG": 1,
  "ALTERNATE aTTaX": 17,
  "ex-AVANGAR": 7,
  "xGOD": 2,
  "hypewrld": 3,
  "MightyWolves": 2,
  "Rebels": 35,
  "Permitta": 13,
  "Enterprise": 13,
  "brazylijski luz": 12,
  "Illuminar": 7,
  "PGE Turow": 4,
  "NAVI Javelins": 2,
  "Permitta W": 1,
  "AMKAL": 58,
  "9 Pandas": 43,
  "PARIVISION": 16,
  "Insilio": 15,
  "RUBY": 14,
  "RUSH B": 13,
  "VP.Prodigy": 12,
  "Space": 10,
  "GUN5": 9,
  "DMS": 8,
  "LEON": 5,
  "LYG": 5,
  "ex-FORZE Ladies": 2,
  "Aurora Young Blud": 2,
  "CYBERSHOKE": 1,
  "Crescent fe": 1,
  "Spirit fe": 1,
  "Ninjas in Pyjamas": 46,
  "Metizport": 29,
  "EYEBALLERS": 15,
  "Johnny Speeds": 13,
  "Alliance": 12,
  "Lilmix": 5,
  "Onliners5": 1,
  "Young Gods": 1,
  "B8": 32,
  "Passion UA": 16,
  "Blessed": 15,
  "ECF": 10,
  "Lazer Cats": 2,
  "L&G": 1,
  "Endpoint": 15,
  "EXO": 5,
  "Verdant": 4,
  "Reason": 4,
  "TYLOO": 45,
  "Lynn Vision": 42,
  "Rare Atom": 11,
  "Steel Helmet": 6,
  "Gods Reign": 5,
  "True Rippers": 2,
  "Marcos": 1,
  "Carnival": 0,
  "Chinggis Warriors": 7,
  "ATOX": 5,
  "IHC": 4,
  "The Huns": 2,
  "Bad News Kangaroos": 26,
  "Rooster": 18,
  "Mindfreak": 8,
  "Vantage": 6,
  "KZG": 5,
  "DXA": 3,
  "Arcade": 2,
  "sunday school": 2,
  "Canon Event": 1
} as Record<string, number>;