export default {
  "Vitality": 973,
  "FaZe": 943,
  "Natus Vincere": 466,
  "Virtus.pro": 443,
  "MOUZ": 436,
  "G2": 404,
  "Cloud9": 324,
  "Complexity": 313,
  "Monte": 311,
  "Apeks": 271,
  "Spirit": 270,
  "FURIA": 249,
  "Falcons": 236,
  "Eternal Fire": 222,
  "Astralis": 196,
  "GamerLegion": 195,
  "MIBR": 147,
  "BetBoom": 146,
  "BIG": 146,
  "Heroic": 133,
  "TheMongolz": 129,
  "HAVU": 120,
  "ENCE": 100,
  "9 Pandas": 100,
  "Liquid": 88,
  "Ninjas in Pyjamas": 65,
  "Rebels": 64,
  "SAW": 52,
  "AMKAL": 51,
  "Preasy": 50,
  "Nouns": 29,
  "timbermen": 28,
  "Wildcard": 28,
  "BOSS": 23,
  "Party Astronauts": 18,
  "Rocket": 17,
  "Carpe Diem": 13,
  "Spectre": 11,
  "my life be like": 10,
  "vagrants": 7,
  "FLUFFY AIMERS": 7,
  "Limitless": 7,
  "Take Flyte": 6,
  "Zomblers": 6,
  "Mythic": 5,
  "Shimmer": 2,
  "Tsunami Sirens": 1,
  "Nouns fe": 1,
  "Imperial": 39,
  "paiN": 29,
  "RED Canids": 25,
  "Legacy": 20,
  "ODDIK": 19,
  "W7M": 18,
  "Sharks": 17,
  "adalYamigos": 13,
  "Case": 13,
  "Flamengo": 12,
  "Fluxo": 11,
  "LOS": 8,
  "Galorys": 7,
  "inSanitY": 4,
  "Corinthians": 4,
  "Solid": 3,
  "FURIA fe": 3,
  "O PLANO": 3,
  "9z Academy": 2,
  "Hype": 2,
  "Fluxo Demons": 2,
  "MIBR fe": 2,
  "Intense": 1,
  "Sojoga": 1,
  "FURIA Academy": 1,
  "W7M fe": 0,
  "ex-Divina fe": 0,
  "SINNERS": 21,
  "ECLOT": 5,
  "ECSTATIC": 39,
  "Sprout": 24,
  "Espionage": 18,
  "Astralis Talent": 10,
  "CEPTER": 4,
  "Sashi": 4,
  "Atlantic": 4,
  "XI": 3,
  "Sashi Academy": 1,
  "JANO": 16,
  "TMVG": 7,
  "Heimo": 3,
  "VIOLET": 0,
  "ALTERNATE aTTaX": 24,
  "BIG Academy": 12,
  "Stealth": 6,
  "CUBE": 4,
  "xGOD": 3,
  "Real Gamers": 1,
  "hypewrld": 9,
  "EC BANGA": 1,
  "sunshine": 1,
  "Enterprise": 34,
  "Permitta": 22,
  "ex-Anonymo": 20,
  "9INE": 11,
  "Illuminar": 9,
  "lajtbitexe": 9,
  "PGE Turow": 7,
  "TUSTE CHOPAKI": 5,
  "NAVI Javelins": 4,
  "ThunderFlash": 2,
  "FORZE": 42,
  "Aurora": 41,
  "Insilio": 18,
  "RUSH B": 18,
  "ILIN": 17,
  "V1dar": 15,
  "Space": 13,
  "Linx Legacy": 13,
  "Nemiga": 11,
  "Aurora Young Blud": 10,
  "GR": 10,
  "RUBY": 10,
  "Spirit Academy": 10,
  "-72c": 8,
  "VP.Prodigy": 8,
  "SGGT": 5,
  "GUN5": 4,
  "Vaseline Worms": 4,
  "LEON": 4,
  "Fort Arena": 4,
  "Memo": 3,
  "OWL": 3,
  "CYBERSHOKE": 2,
  "1WIN Academy": 2,
  "Metizport": 26,
  "EYEBALLERS": 21,
  "GODSENT": 20,
  "Alliance": 15,
  "Young Ninjas": 12,
  "Lilmix": 6,
  "Onliners5": 5,
  "Kappa Bar": 3,
  "ESC": 13,
  "B8": 12,
  "Passion UA": 11,
  "ENEIDA": 10,
  "Endpoint": 16,
  "SRK": 8,
  "Verdant": 8,
  "Lynn Vision": 33,
  "TYLOO": 33,
  "Rare Atom": 15,
  "Newhappy": 13,
  "Wings Up": 9,
  "E9": 9,
  "Steel Helmet": 8,
  "SHPL": 5,
  "Nirvana": 3,
  "DNA": 0,
  "2ez": 5,
  "Gods Reign": 4,
  "Marcos": 3,
  "True Rippers": 2,
  "Enigma": 1,
  "Grayfox": 1,
  "The Huns": 13,
  "ATOX": 12,
  "Eruption": 8,
  "Chinggis Warriors": 2,
  "Grayhound": 31,
  "Bad News Kangaroos": 15,
  "Rooster": 15,
  "Mindfreak": 11,
  "Vantage": 7,
  "DXA": 5,
  "RKON": 3,
  "KZG": 3,
  "iM Apartments": 2,
  "Stirlzs Angels": 2,
  "Antic": 1,
  "disciples": 1
} as Record<string, number>;